site_name: Quadratic Courses
site_url: https://elwennjoubrel-quadreatic.github.io/autoformation
site_dir: public
repo_url: https://github.com/elwennjoubrel-quadratic/autoformation
repo_name: ejoubrel/power-docs

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  language: fr
  font:
    text: Barlow
    code: Jetbrains Mono
  logo: assets/logo_mauve.png
  favicon: assets/favicon.ico
  icon:
    annotation: material/plus-circle-outline
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    repo: fontawesome/brands/gitlab
  palette:
    - scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/eye
        name: Switch to light mode
      primary: custom
      accent: custom
  features:
    - navigation.instant
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.top
    # - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotate

extra:
  social:
    - icon: material/web
      link: https://www.quadratic-labs.com
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Quadratic-Labs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/quadratic-labs
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

copyright: |
  &copy; 2024 <a href="https://www.quadratic-labs.com/"  target="_blank" rel="noopener">Quadratic Labs</a>



nav:
  - 'index.md'
  - Python:
    - 'pages/python/index.md'
    - Débutant:
      - 'pages/python/debutant/installation.md'
      - 'pages/python/debutant/notions.md'
      - 'pages/python/debutant/operateurs.md'
      - 'pages/python/debutant/fonctionsPackagesModules.md'
      - 'pages/python/debutant/dataScience.md'
      - 'pages/python/debutant/modelisation.md'
  - Docker:
    - 'pages/docker/index.md'
  - FastAPI:
    - 'pages/fastapi/index.md'
    - 'pages/fastapi/introduction.md'
    - 'pages/fastapi/routers.md'
    - Advanced:
      - 'pages/fastapi/advanced/index.md'
      - 'pages/fastapi/advanced/authentication.md'
  - 'about.md'